export interface Course {
  id: string;
  name: string;
  category: string; // Primary sidebar category
  subCategories?: string[]; // Additional sidebar categories this course appears in
  level: 'UG' | 'PG' | 'Diploma' | 'ITI' | 'Skill' | 'Apprenticeship' | 'Certificate';
  duration: string;
  eligibility: string;
  mode: 'Regular' | 'Online' | 'Hybrid';
  badge?: string;
  description: string;
  fees: string;
  seats: number;
  careerOpportunities: string[];
  placementSupport: string;
  iconName: 'computer' | 'gear' | 'wrench' | 'briefcase' | 'database' | 'cpu' | 'building' | 'chart' | 'network' | 'bolt' | 'flame' | 'sparkles';
}

export const courseCategories = [
  'Undergraduate (UG)',
  'Postgraduate (PG)',
  'Engineering',
  'Computer & IT',
  'Commerce',
  'Science',
  'Arts & Humanities',
  'Management',
  'Law',
  'Health & Allied Science',
  'Yoga & Naturopathy',
  'Journalism & Mass Communication',
  'Library Science',
  'Diploma Courses',
  'ITI Trades',
  'Skill Development',
  'Apprenticeship Programs',
  'Government Approved Courses',
];

export const courseList: Course[] = [

  // ==================== ENGINEERING ====================
  {
    id: 'btech-cse',
    name: 'B.Tech - Computer Science Engineering',
    category: 'Engineering',
    subCategories: ['Undergraduate (UG)', 'Computer & IT'],
    level: 'UG',
    duration: '4 Years',
    eligibility: '10+2 with PCM, 50% marks',
    mode: 'Regular',
    badge: 'Most Popular',
    description: 'Full B.Tech degree in Computer Science covering software engineering, algorithms, databases, AI, and web technologies.',
    fees: 'Contact Admissions Desk',
    seats: 120,
    careerOpportunities: ['Software Developer', 'Full Stack Engineer', 'System Architect', 'Database Admin'],
    placementSupport: 'Dedicated technical placement cell with direct corporate tie-ups.',
    iconName: 'computer',
  },
  {
    id: 'btech-me',
    name: 'B.Tech - Mechanical Engineering',
    category: 'Engineering',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '4 Years',
    eligibility: '10+2 with PCM, 50% marks',
    mode: 'Regular',
    badge: 'Industry Ready',
    description: 'Comprehensive mechanical engineering curriculum covering thermodynamics, CNC, CAD/CAM, robotics and manufacturing processes.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Design Engineer', 'Plant Head', 'Quality Inspector', 'Automotive Specialist'],
    placementSupport: 'Direct industrial apprentice linkages with core industries.',
    iconName: 'gear',
  },
  {
    id: 'btech-ce',
    name: 'B.Tech - Civil Engineering',
    category: 'Engineering',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '4 Years',
    eligibility: '10+2 with PCM, 50% marks',
    mode: 'Regular',
    badge: 'Top Choice',
    description: 'Study structural engineering, geotechnics, construction management, environmental engineering and survey techniques.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Site Engineer', 'Structural Designer', 'Project Estimator', 'Urban Planner'],
    placementSupport: 'Guidance for state and central government infrastructure hiring.',
    iconName: 'building',
  },
  {
    id: 'btech-ee',
    name: 'B.Tech - Electrical Engineering',
    category: 'Engineering',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '4 Years',
    eligibility: '10+2 with PCM, 50% marks',
    mode: 'Regular',
    badge: 'Job Oriented',
    description: 'Power systems, electrical machines, control systems, renewable energy grids and transmission network engineering.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Power Grid Inspector', 'Substation Engineer', 'Electrical Design Analyst', 'Maintenance Specialist'],
    placementSupport: 'Placement assistance with state power utilities, railways and private energy corps.',
    iconName: 'bolt',
  },
  {
    id: 'btech-extc',
    name: 'B.Tech - Electronics & Telecommunication',
    category: 'Engineering',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '4 Years',
    eligibility: '10+2 with PCM, 50% marks',
    mode: 'Regular',
    badge: 'Top Choice',
    description: 'Telecom networks, embedded systems, VLSI designs, signal processing and high-frequency communication pathways.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Telecom Network Engineer', 'Embedded Systems Dev', 'RF Analyst', 'Electronics Designer'],
    placementSupport: 'Placements with major telecom operators and semiconductor firms.',
    iconName: 'network',
  },
  {
    id: 'btech-it',
    name: 'B.Tech - Information Technology',
    category: 'Engineering',
    subCategories: ['Undergraduate (UG)', 'Computer & IT'],
    level: 'UG',
    duration: '4 Years',
    eligibility: '10+2 with PCM, 50% marks',
    mode: 'Regular',
    badge: 'High Placement',
    description: 'Cloud computing, cybersecurity, database administration, business networking and digital transformation technologies.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Cloud Engineer', 'Network Administrator', 'Cybersecurity Analyst', 'IT Project Manager'],
    placementSupport: 'Corporate alignment with IT services companies and tech centers.',
    iconName: 'database',
  },
  {
    id: 'btech-le',
    name: 'B.Tech - Lateral Entry',
    category: 'Engineering',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '3 Years',
    eligibility: 'Diploma in Engineering / B.Sc with PCM',
    mode: 'Regular',
    badge: 'Lateral Entry',
    description: 'Direct 2nd year B.Tech admission for diploma holders and B.Sc graduates in engineering streams.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Engineer', 'Technical Consultant', 'Production Supervisor', 'Site Engineer'],
    placementSupport: 'Same placement support as regular B.Tech batch.',
    iconName: 'gear',
  },
  {
    id: 'mtech-cse',
    name: 'M.Tech - Computer Science Engineering',
    category: 'Engineering',
    subCategories: ['Postgraduate (PG)', 'Computer & IT'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'B.Tech/B.E. in relevant field',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Advanced postgraduate study in machine learning, advanced algorithms, cloud computing and systems design.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Senior Software Architect', 'R&D Engineer', 'ML Researcher', 'Tech Lead'],
    placementSupport: 'PG placement cell with research and industry linkages.',
    iconName: 'computer',
  },
  {
    id: 'mtech-me',
    name: 'M.Tech - Mechanical Engineering',
    category: 'Engineering',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'B.Tech/B.E. in Mechanical or related',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Advanced manufacturing, thermal engineering, CAD/CAM automation and industrial robotics at postgraduate level.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['Senior Design Engineer', 'R&D Specialist', 'Manufacturing Head', 'Quality Lead'],
    placementSupport: 'Industry and research placement linkages.',
    iconName: 'gear',
  },
  {
    id: 'dip-eng-mech',
    name: 'Diploma Engineering - Mechanical',
    category: 'Diploma Courses',
    subCategories: ['Engineering'],
    level: 'Diploma',
    duration: '3 Years',
    eligibility: '10th Passed with Science & Math',
    mode: 'Regular',
    badge: 'Industry Ready',
    description: 'Diploma covering metal cutting, CNC operations, thermodynamics, production design and shop-floor management.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Junior Design Engineer', 'CNC Operator', 'Maintenance Technician', 'Production Supervisor'],
    placementSupport: 'Direct apprenticeships with core industrial factories.',
    iconName: 'gear',
  },
  {
    id: 'dip-eng-civil',
    name: 'Diploma Engineering - Civil',
    category: 'Diploma Courses',
    subCategories: ['Engineering'],
    level: 'Diploma',
    duration: '3 Years',
    eligibility: '10th Passed with Science & Math',
    mode: 'Regular',
    badge: 'Government Approved',
    description: 'Building drafting, soil testing, concrete layouting, survey equipment operations and project estimation.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Site Surveyor', 'Assistant Site Engineer', 'Draftsman', 'Civil Estimator'],
    placementSupport: 'Assistance in state contractor registrations and construction companies.',
    iconName: 'building',
  },
  {
    id: 'dip-eng-comp',
    name: 'Diploma Engineering - Computer',
    category: 'Diploma Courses',
    subCategories: ['Engineering', 'Computer & IT'],
    level: 'Diploma',
    duration: '3 Years',
    eligibility: '10th Passed with Science & Math',
    mode: 'Regular',
    badge: 'Most Popular',
    description: 'Coding fundamentals, hardware installation, database management, web layouts and systems security setups.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Junior Web Developer', 'IT Support Specialist', 'Network Associate', 'Testing Assistant'],
    placementSupport: 'Direct placements at IT services firms and system integrators.',
    iconName: 'computer',
  },
  {
    id: 'dip-eng-elec',
    name: 'Diploma Engineering - Electrical',
    category: 'Diploma Courses',
    subCategories: ['Engineering'],
    level: 'Diploma',
    duration: '3 Years',
    eligibility: '10th Passed with Science & Math',
    mode: 'Regular',
    badge: 'Job Oriented',
    description: 'Power networks, substation layouts, motor systems repair, domestic grid installations and wiring blueprint reviews.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Electrical Substation Helper', 'Maintenance Operator', 'Solar Wiring Operator', 'Power Inspector'],
    placementSupport: 'Linkages with energy contractors and state utilities.',
    iconName: 'bolt',
  },
  {
    id: 'dip-eng-le',
    name: 'Diploma Engineering - Lateral Entry',
    category: 'Diploma Courses',
    subCategories: ['Engineering'],
    level: 'Diploma',
    duration: '2 Years',
    eligibility: 'ITI Passed in relevant trade',
    mode: 'Regular',
    badge: 'Lateral Entry',
    description: 'Lateral admission into 2nd year of diploma engineering for ITI trade pass-outs.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Diploma Technician', 'Workshop Supervisor', 'Junior Engineer', 'Site Technician'],
    placementSupport: 'Same support as regular diploma batch with ITI background advantage.',
    iconName: 'gear',
  },

  // ==================== COMPUTER & IT ====================
  {
    id: 'bca',
    name: 'BCA - Bachelor of Computer Applications',
    category: 'Computer & IT',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in any stream, 45% marks',
    mode: 'Regular',
    badge: 'Most Popular',
    description: 'Comprehensive undergraduate program in computer applications, programming, software development and database management.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Software Developer', 'Web Developer', 'Database Analyst', 'IT Support Executive'],
    placementSupport: 'Strong placement network with software and IT services companies.',
    iconName: 'computer',
  },
  {
    id: 'mca',
    name: 'MCA - Master of Computer Applications',
    category: 'Computer & IT',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'BCA / B.Sc IT / B.Sc CS or equivalent',
    mode: 'Regular',
    badge: 'High Placement',
    description: 'Advanced postgraduate program in software engineering, advanced programming, networking and enterprise applications.',
    fees: 'Contact Admissions Desk',
    seats: 40,
    careerOpportunities: ['Senior Developer', 'Systems Analyst', 'Software Architect', 'IT Consultant'],
    placementSupport: 'Corporate linkages with IT majors and software product companies.',
    iconName: 'computer',
  },
  {
    id: 'dca',
    name: 'DCA - Diploma in Computer Applications',
    category: 'Computer & IT',
    subCategories: ['Undergraduate (UG)', 'Diploma Courses', 'Skill Development'],
    level: 'Diploma',
    duration: '1 Year',
    eligibility: '10th or 10+2 Passed',
    mode: 'Regular',
    badge: 'Skill India',
    description: 'Short-term diploma covering office tools, internet usage, basic programming, hardware fundamentals and data entry.',
    fees: 'Contact Admissions Desk',
    seats: 40,
    careerOpportunities: ['Computer Operator', 'Data Entry Clerk', 'Office Assistant', 'IT Support Helper'],
    placementSupport: 'Job linkages at offices, educational institutions and IT firms.',
    iconName: 'computer',
  },
  {
    id: 'pgdca',
    name: 'PGDCA - PG Diploma in Computer Applications',
    category: 'Computer & IT',
    subCategories: ['Postgraduate (PG)', 'Diploma Courses'],
    level: 'PG',
    duration: '1 Year',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'PG Diploma',
    description: 'Postgraduate diploma program in advanced computer applications, database management, web technologies and networking.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['IT Coordinator', 'Systems Administrator', 'Web Developer', 'Database Manager'],
    placementSupport: 'Placement assistance with IT firms and corporate offices.',
    iconName: 'computer',
  },
  {
    id: 'bsc-it',
    name: 'B.Sc - Information Technology',
    category: 'Computer & IT',
    subCategories: ['Undergraduate (UG)', 'Science'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    mode: 'Regular',
    badge: 'Job Oriented',
    description: 'UG science program focused on IT fundamentals, programming, databases, networking and software development.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['IT Analyst', 'Software Developer', 'Network Engineer', 'Systems Admin'],
    placementSupport: 'Placement linkages with mid-size and enterprise IT companies.',
    iconName: 'database',
  },
  {
    id: 'bsc-cs',
    name: 'B.Sc - Computer Science',
    category: 'Computer & IT',
    subCategories: ['Undergraduate (UG)', 'Science'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 with PCM / PCB',
    mode: 'Regular',
    badge: 'Trending',
    description: 'Computer science degree covering algorithms, data structures, operating systems, AI fundamentals and software engineering.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Software Engineer', 'AI Developer', 'Data Analyst', 'Software Tester'],
    placementSupport: 'Tech placement cell with strong software company network.',
    iconName: 'cpu',
  },
  {
    id: 'bsc-ds',
    name: 'B.Sc - Data Science',
    category: 'Computer & IT',
    subCategories: ['Undergraduate (UG)', 'Science'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 with Math',
    mode: 'Hybrid',
    badge: 'Trending',
    description: 'Data analytics, machine learning fundamentals, statistical modeling, Python/R programming and visualization tools.',
    fees: 'Contact Admissions Desk',
    seats: 40,
    careerOpportunities: ['Data Analyst', 'BI Developer', 'Data Engineer', 'ML Engineer'],
    placementSupport: 'Analytics placement network with data-driven companies.',
    iconName: 'chart',
  },
  {
    id: 'msc-it',
    name: 'M.Sc - Information Technology',
    category: 'Computer & IT',
    subCategories: ['Postgraduate (PG)', 'Science'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'B.Sc IT / BCA or equivalent',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Advanced IT concepts including cloud infrastructure, enterprise systems, cybersecurity and software architecture.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Senior IT Analyst', 'Cloud Architect', 'Security Engineer', 'Systems Manager'],
    placementSupport: 'PG placement linkages with IT service majors.',
    iconName: 'database',
  },
  {
    id: 'msc-cs',
    name: 'M.Sc - Computer Science',
    category: 'Computer & IT',
    subCategories: ['Postgraduate (PG)', 'Science'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'B.Sc CS / BCA or equivalent',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Advanced algorithms, machine learning, distributed systems, research-oriented computing and advanced software engineering.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Research Scientist', 'ML Engineer', 'Senior Developer', 'AI Specialist'],
    placementSupport: 'Research and industry placement linkages.',
    iconName: 'cpu',
  },
  {
    id: 'msc-ds',
    name: 'M.Sc - Data Science',
    category: 'Computer & IT',
    subCategories: ['Postgraduate (PG)', 'Science'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'B.Sc / B.Tech with Math/Stats background',
    mode: 'Hybrid',
    badge: 'Trending',
    description: 'Deep learning, big data analytics, predictive modeling, NLP and advanced data engineering at postgraduate level.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['Data Scientist', 'ML Researcher', 'Analytics Lead', 'AI Product Manager'],
    placementSupport: 'Analytics and AI company placement network.',
    iconName: 'chart',
  },
  {
    id: 'pg-dip-aiml',
    name: 'PG Diploma - AI & Machine Learning',
    category: 'Computer & IT',
    subCategories: ['Postgraduate (PG)', 'Skill Development', 'Diploma Courses'],
    level: 'PG',
    duration: '1 Year',
    eligibility: 'Any Graduate with Math background',
    mode: 'Hybrid',
    badge: 'New',
    description: 'Industry-focused program in artificial intelligence, machine learning pipelines, deep learning frameworks and real-world AI deployment.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['AI Engineer', 'ML Specialist', 'Data Engineer', 'AI Product Analyst'],
    placementSupport: 'Linkages with AI-first companies and tech startups.',
    iconName: 'cpu',
  },

  // ==================== COMMERCE ====================
  {
    id: 'bcom',
    name: 'B.Com - Bachelor of Commerce',
    category: 'Commerce',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in Commerce / any stream, 45%',
    mode: 'Regular',
    badge: 'Most Popular',
    description: 'Foundational commerce education covering accounting, business law, economics, taxation and financial management.',
    fees: 'Contact Admissions Desk',
    seats: 120,
    careerOpportunities: ['Accountant', 'Tax Consultant', 'Finance Officer', 'Business Analyst'],
    placementSupport: 'Commerce placement cell with corporate and banking linkages.',
    iconName: 'briefcase',
  },
  {
    id: 'bcom-bf',
    name: 'B.Com - Banking & Finance',
    category: 'Commerce',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in Commerce / any stream',
    mode: 'Regular',
    badge: 'Job Oriented',
    description: 'Specialized commerce degree focused on banking operations, financial markets, investment analysis and credit management.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Bank Officer', 'Financial Analyst', 'Credit Manager', 'Insurance Executive'],
    placementSupport: 'Banking sector placement channels.',
    iconName: 'chart',
  },
  {
    id: 'bcom-ca',
    name: 'B.Com - Computer Application',
    category: 'Commerce',
    subCategories: ['Undergraduate (UG)', 'Computer & IT'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    mode: 'Regular',
    badge: 'Trending',
    description: 'Commerce degree integrated with computer applications, ERP, Tally, digital accounting and business software.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Accounts Executive', 'ERP Operator', 'Office Admin', 'Data Entry Specialist'],
    placementSupport: 'Placement support with commerce and IT hybrid roles.',
    iconName: 'computer',
  },
  {
    id: 'mcom',
    name: 'M.Com - Master of Commerce',
    category: 'Commerce',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'B.Com or equivalent graduation',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Advanced commerce education in research methodology, advanced accounting, corporate law, taxation and auditing.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Senior Accountant', 'Finance Manager', 'Auditor', 'Tax Specialist'],
    placementSupport: 'Finance and accounting placement channels.',
    iconName: 'briefcase',
  },

  // ==================== SCIENCE ====================
  {
    id: 'bsc',
    name: 'B.Sc - Bachelor of Science',
    category: 'Science',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 with PCM or PCB, 45%',
    mode: 'Regular',
    badge: 'Classic Program',
    description: 'General science degree in Physics, Chemistry, Mathematics or Biology with lab-based practical learning.',
    fees: 'Contact Admissions Desk',
    seats: 120,
    careerOpportunities: ['Lab Technician', 'Research Assistant', 'Science Teacher', 'Quality Analyst'],
    placementSupport: 'Science and research institution linkages.',
    iconName: 'sparkles',
  },
  {
    id: 'bsc-hons',
    name: 'B.Sc (Hons) - Bachelor of Science Honors',
    category: 'Science',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 with PCM or PCB, 55%',
    mode: 'Regular',
    badge: 'Honours Degree',
    description: 'Research-intensive honors science program with specialization in a core science subject.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Research Scientist', 'Lab Analyst', 'R&D Specialist', 'Academic Faculty'],
    placementSupport: 'Research lab and industry linkages.',
    iconName: 'sparkles',
  },
  {
    id: 'msc',
    name: 'M.Sc - Master of Science',
    category: 'Science',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'B.Sc in relevant subject, 50%',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Advanced postgraduate science degree with research projects, lab work and specialization in physics, chemistry or math.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Senior Scientist', 'Research Fellow', 'Lab Head', 'Science Consultant'],
    placementSupport: 'Research institutions and science industry linkages.',
    iconName: 'sparkles',
  },

  // ==================== ARTS & HUMANITIES ====================
  {
    id: 'ba',
    name: 'BA - Bachelor of Arts',
    category: 'Arts & Humanities',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in any stream, 40%',
    mode: 'Regular',
    badge: 'Classic Program',
    description: 'General arts degree covering humanities, social science, literature, history, political science and sociology.',
    fees: 'Contact Admissions Desk',
    seats: 120,
    careerOpportunities: ['Civil Services', 'Teacher', 'Content Writer', 'HR Executive'],
    placementSupport: 'Soft skills and government exam guidance support.',
    iconName: 'network',
  },
  {
    id: 'ba-hons',
    name: 'BA (Hons) - Bachelor of Arts Honors',
    category: 'Arts & Humanities',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in any stream, 50%',
    mode: 'Regular',
    badge: 'Honours Degree',
    description: 'Research-oriented arts honors program with specialization in one subject and academic depth.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Academic Researcher', 'Content Strategist', 'Civil Services', 'Media Professional'],
    placementSupport: 'Media, NGO and government sector linkages.',
    iconName: 'network',
  },
  {
    id: 'bsw',
    name: 'BSW - Bachelor of Social Work',
    category: 'Arts & Humanities',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    mode: 'Regular',
    badge: 'Social Impact',
    description: 'Social work education covering community development, NGO operations, counseling, rural outreach and welfare programs.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Social Worker', 'NGO Manager', 'Community Organizer', 'Welfare Officer'],
    placementSupport: 'NGO and social sector placement network.',
    iconName: 'network',
  },
  {
    id: 'ma',
    name: 'MA - Master of Arts',
    category: 'Arts & Humanities',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'BA or equivalent graduation',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Advanced arts and humanities postgraduate program with specialization in sociology, political science or literature.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Researcher', 'Lecturer', 'Media Analyst', 'Civil Services'],
    placementSupport: 'Academic and public sector linkages.',
    iconName: 'network',
  },
  {
    id: 'msw',
    name: 'MSW - Master of Social Work',
    category: 'Arts & Humanities',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'BSW or any graduation',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Advanced social work management, research, policy advocacy, rural development and community leadership.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Senior Social Worker', 'NGO Director', 'Policy Researcher', 'Welfare Head'],
    placementSupport: 'Senior NGO and government social sector linkages.',
    iconName: 'network',
  },

  // ==================== MANAGEMENT ====================
  {
    id: 'bba',
    name: 'BBA - Bachelor of Business Administration',
    category: 'Management',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in any stream, 45%',
    mode: 'Regular',
    badge: 'Most Popular',
    description: 'Foundation business management program covering marketing, finance, HR, operations and entrepreneurship.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Business Executive', 'Marketing Coordinator', 'HR Assistant', 'Sales Officer'],
    placementSupport: 'Management sector placement cell.',
    iconName: 'briefcase',
  },
  {
    id: 'mba-mkt',
    name: 'MBA - Marketing',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'Most Popular',
    description: 'Advanced management training in consumer analytics, branding, digital marketing, advertising and strategic sales.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Marketing Director', 'Brand Manager', 'Sales Strategist', 'Market Analyst'],
    placementSupport: 'Placements with FMCG, retail and digital marketing agencies.',
    iconName: 'chart',
  },
  {
    id: 'mba-fin',
    name: 'MBA - Finance',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'Top Choice',
    description: 'Corporate finance, investment portfolios, wealth management, risk models and quantitative financial analysis.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Financial Controller', 'Investment Analyst', 'Portfolio Manager', 'Credit Risk Officer'],
    placementSupport: 'Tie-ups with banks, fintech startups and audit consultants.',
    iconName: 'briefcase',
  },
  {
    id: 'mba-hr',
    name: 'MBA - Human Resource',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'Job Oriented',
    description: 'Employee relations, talent acquisition, organizational design, HR compliance, reward systems and labor laws.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['HR Manager', 'Talent Acquisition Head', 'Corporate Trainer', 'HR Operations Lead'],
    placementSupport: 'HR placement channels with service and tech firms.',
    iconName: 'network',
  },
  {
    id: 'mba-ops',
    name: 'MBA - Operations',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'Industry Ready',
    description: 'Process optimization, warehousing, quality methodologies (Six Sigma), procurement and project management.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['Operations Analyst', 'Warehouse Manager', 'Quality Head', 'Supply Chain Analyst'],
    placementSupport: 'Placements with manufacturing, automotive and logistics firms.',
    iconName: 'gear',
  },
  {
    id: 'mba-ba',
    name: 'MBA - Business Analytics',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'Trending',
    description: 'Data-driven decision making, predictive analytics, dashboarding and business intelligence tools for managers.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['Business Analyst', 'Data Strategy Consultant', 'Analytics Lead', 'BI Manager'],
    placementSupport: 'Consulting firms and analytics company linkages.',
    iconName: 'chart',
  },
  {
    id: 'mba-scm',
    name: 'MBA - Supply Chain & Logistics',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'Industry Ready',
    description: 'Freight operations, demand planning, procurement, container management and vendor quality control.',
    fees: 'Contact Admissions Desk',
    seats: 15,
    careerOpportunities: ['Supply Chain Coordinator', 'Logistics Analyst', 'Procurement Strategist', 'Inventory Controller'],
    placementSupport: 'E-commerce, shipping and retail firm placements.',
    iconName: 'briefcase',
  },
  {
    id: 'mba-ib',
    name: 'MBA - International Business',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'Government Approved',
    description: 'Cross-border trade guidelines, international finance, global compliance networks and multinational corporate logistics.',
    fees: 'Contact Admissions Desk',
    seats: 15,
    careerOpportunities: ['Global Logistics Manager', 'International Trade Specialist', 'Export-Import Head', 'Trade Advisor'],
    placementSupport: 'Trade corporations and global freight organizations.',
    iconName: 'network',
  },
  {
    id: 'mba-hm',
    name: 'MBA - Hospital Management',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'Top Choice',
    description: 'Hospital operations, clinical process audits, public health policies, medical insurance frameworks and administration.',
    fees: 'Contact Admissions Desk',
    seats: 15,
    careerOpportunities: ['Hospital Administrator', 'Healthcare Planner', 'Clinical Audit Coordinator', 'Medical Operations Head'],
    placementSupport: 'Hospital chains, healthcare trusts and insurance providers.',
    iconName: 'building',
  },
  {
    id: 'mba-rm',
    name: 'MBA - Retail Management',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'Skill India',
    description: 'Multi-channel retailing, franchise networks, store operations, customer engagement and visual merchandising.',
    fees: 'Contact Admissions Desk',
    seats: 15,
    careerOpportunities: ['Store Director', 'Retail Operations Analyst', 'Merchandising Coordinator', 'Franchise Manager'],
    placementSupport: 'Organized retail groups and consumer brand placements.',
    iconName: 'briefcase',
  },
  {
    id: 'mba-ent',
    name: 'MBA - Entrepreneurship',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'Trending',
    description: 'New venture creation, business blueprints, investor pitching, capital valuation, IP and startup ecosystem.',
    fees: 'Contact Admissions Desk',
    seats: 15,
    careerOpportunities: ['Startup Founder', 'Venture Partner', 'Incubator Specialist', 'Innovation Director'],
    placementSupport: 'Startup incubators, seed funds and acceleration labs.',
    iconName: 'sparkles',
  },
  {
    id: 'mba-it',
    name: 'MBA - Information Technology',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'Job Oriented',
    description: 'Bridge between technology management and business: IT resources, software lifecycle, security audits and cloud strategy.',
    fees: 'Contact Admissions Desk',
    seats: 15,
    careerOpportunities: ['IT Infrastructure Lead', 'CTO Trainee', 'Tech Project Analyst', 'IT Vendor Manager'],
    placementSupport: 'Global consulting desks and systems integrators.',
    iconName: 'cpu',
  },
  {
    id: 'emba',
    name: 'EMBA - Executive MBA',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '1 Year',
    eligibility: 'Graduate with 5+ Years Work Experience',
    mode: 'Online',
    badge: 'Executive Program',
    description: 'Weekend/online MBA program for working professionals covering leadership, strategy, finance and organizational management.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['Senior Manager', 'Director', 'Business Leader', 'Department Head'],
    placementSupport: 'Senior executive roles in corporate network.',
    iconName: 'briefcase',
  },
  {
    id: 'pgdba',
    name: 'PGDBA - PG Diploma in Business Administration',
    category: 'Management',
    subCategories: ['Postgraduate (PG)', 'Diploma Courses'],
    level: 'PG',
    duration: '1 Year',
    eligibility: 'Any Graduate',
    mode: 'Hybrid',
    badge: 'PG Diploma',
    description: 'Short postgraduate diploma in business fundamentals, management principles, leadership and corporate strategy.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Business Executive', 'Team Lead', 'Manager Trainee', 'Operations Coordinator'],
    placementSupport: 'Corporate fast-track placement channels.',
    iconName: 'briefcase',
  },
  {
    id: 'dba',
    name: 'DBA - Doctorate in Business Administration',
    category: 'Management',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '3 Years',
    eligibility: 'MBA / PGDBA with Work Experience',
    mode: 'Hybrid',
    badge: 'Doctorate',
    description: 'Research-level business administration degree for senior professionals and academic aspirants.',
    fees: 'Contact Admissions Desk',
    seats: 10,
    careerOpportunities: ['Professor', 'Research Head', 'Management Consultant', 'C-Suite Executive'],
    placementSupport: 'Academic and senior leadership placement network.',
    iconName: 'briefcase',
  },

  // ==================== LAW ====================
  {
    id: 'llm',
    name: 'LLM - Master of Laws',
    category: 'Law',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'LLB or equivalent law degree',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Advanced legal education with specializations in corporate law, constitutional law, human rights and international law.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Senior Advocate', 'Legal Consultant', 'Law Professor', 'Corporate Counsel'],
    placementSupport: 'Legal firms, courts and corporate legal department placements.',
    iconName: 'building',
  },

  // ==================== HEALTH & ALLIED SCIENCE ====================
  {
    id: 'ba-pub-health',
    name: 'BA (Hons) - Public Health',
    category: 'Health & Allied Science',
    subCategories: ['Undergraduate (UG)', 'Arts & Humanities'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    mode: 'Regular',
    badge: 'Health Program',
    description: 'Study public health policy, epidemiology, community medicine, health systems and social determinants of health.',
    fees: 'Contact Admissions Desk',
    seats: 40,
    careerOpportunities: ['Public Health Officer', 'Health Policy Analyst', 'Community Health Worker', 'NGO Health Manager'],
    placementSupport: 'Government health departments and NGO health sector placements.',
    iconName: 'sparkles',
  },

  // ==================== YOGA & NATUROPATHY ====================
  {
    id: 'bsc-yoga',
    name: 'B.Sc - Yoga',
    category: 'Yoga & Naturopathy',
    subCategories: ['Undergraduate (UG)', 'Science'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    mode: 'Regular',
    badge: 'Wellness Program',
    description: 'Scientific study of yoga anatomy, physiology, asanas, pranayama, therapeutic yoga and yogic philosophy.',
    fees: 'Contact Admissions Desk',
    seats: 40,
    careerOpportunities: ['Yoga Instructor', 'Wellness Coach', 'Yoga Therapist', 'Fitness Trainer'],
    placementSupport: 'Wellness centers, schools and corporate yoga program placements.',
    iconName: 'sparkles',
  },
  {
    id: 'ba-yoga',
    name: 'BA - Yoga',
    category: 'Yoga & Naturopathy',
    subCategories: ['Undergraduate (UG)', 'Arts & Humanities'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    mode: 'Regular',
    badge: 'Wellness Program',
    description: 'Arts-stream yoga program covering yogic philosophy, Indian classical texts, meditation and holistic wellness.',
    fees: 'Contact Admissions Desk',
    seats: 40,
    careerOpportunities: ['Yoga Teacher', 'Meditation Coach', 'Retreat Coordinator', 'Wellness Manager'],
    placementSupport: 'Ashrams, wellness retreats and schools.',
    iconName: 'sparkles',
  },
  {
    id: 'dip-yoga',
    name: 'Diploma in Yoga',
    category: 'Yoga & Naturopathy',
    subCategories: ['Diploma Courses'],
    level: 'Diploma',
    duration: '1 Year',
    eligibility: '10+2 or equivalent',
    mode: 'Regular',
    badge: 'Diploma',
    description: 'Practical yoga training covering asana techniques, teaching methodology, yoga for health and basic anatomy.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Yoga Teacher', 'Fitness Instructor', 'Wellness Center Staff'],
    placementSupport: 'Yoga studios and fitness centers.',
    iconName: 'sparkles',
  },
  {
    id: 'dip-naturopathy',
    name: 'Diploma in Naturopathy',
    category: 'Yoga & Naturopathy',
    subCategories: ['Diploma Courses'],
    level: 'Diploma',
    duration: '1 Year',
    eligibility: '10+2 in any stream',
    mode: 'Regular',
    badge: 'Diploma',
    description: 'Natural healing methods, hydrotherapy, diet therapy, fasting therapy, mud therapy and holistic health concepts.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Naturopathy Therapist', 'Wellness Consultant', 'Health Coach'],
    placementSupport: 'Naturopathy clinics and wellness centers.',
    iconName: 'sparkles',
  },
  {
    id: 'ma-yoga',
    name: 'MA - Yoga',
    category: 'Yoga & Naturopathy',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduation',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Advanced yoga philosophy, research, classical texts, yogic psychology and teacher training at postgraduate level.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Senior Yoga Teacher', 'Yoga Researcher', 'Wellness Director', 'Academia Faculty'],
    placementSupport: 'Research and senior wellness sector placements.',
    iconName: 'sparkles',
  },
  {
    id: 'msc-yoga',
    name: 'M.Sc - Yoga',
    category: 'Yoga & Naturopathy',
    subCategories: ['Postgraduate (PG)', 'Science'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'B.Sc Yoga or B.Sc in Life Sciences',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Scientific postgraduate program in yoga therapy, sports yoga, clinical research and advanced physiology.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['Clinical Yoga Therapist', 'Sports Yoga Coach', 'Research Analyst', 'Yoga Educator'],
    placementSupport: 'Hospitals, research centers and sports organizations.',
    iconName: 'sparkles',
  },
  {
    id: 'pg-dip-yoga',
    name: 'PG Diploma in Yoga',
    category: 'Yoga & Naturopathy',
    subCategories: ['Postgraduate (PG)', 'Diploma Courses'],
    level: 'PG',
    duration: '1 Year',
    eligibility: 'Any Graduation',
    mode: 'Hybrid',
    badge: 'PG Diploma',
    description: 'Short postgraduate diploma in advanced yoga techniques, therapeutic applications and yoga management.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['Yoga Instructor', 'Corporate Wellness Trainer', 'Rehabilitation Yoga Specialist'],
    placementSupport: 'Wellness centers and corporate wellness programs.',
    iconName: 'sparkles',
  },

  // ==================== JOURNALISM & MASS COMM ====================
  {
    id: 'bjmc',
    name: 'BJMC - Bachelor of Journalism & Mass Communication',
    category: 'Journalism & Mass Communication',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    mode: 'Regular',
    badge: 'Media Program',
    description: 'Media studies, journalism ethics, reporting, TV production, digital media, PR, advertising and broadcasting.',
    fees: 'Contact Admissions Desk',
    seats: 40,
    careerOpportunities: ['Journalist', 'News Anchor', 'PR Manager', 'Content Creator'],
    placementSupport: 'Media houses, PR firms and digital agency placements.',
    iconName: 'network',
  },
  {
    id: 'mjmc',
    name: 'MJMC - Master of Journalism & Mass Communication',
    category: 'Journalism & Mass Communication',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '2 Years',
    eligibility: 'Any Graduation',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Advanced journalism, investigative reporting, broadcast media, digital journalism and media management.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Senior Journalist', 'Editor', 'Media Director', 'Digital Media Head'],
    placementSupport: 'National media houses, news agencies and digital platforms.',
    iconName: 'network',
  },

  // ==================== LIBRARY SCIENCE ====================
  {
    id: 'blib',
    name: 'B.Lib - Bachelor of Library Science',
    category: 'Library Science',
    subCategories: ['Undergraduate (UG)'],
    level: 'UG',
    duration: '1 Year',
    eligibility: 'Any Graduation',
    mode: 'Regular',
    badge: 'Library Program',
    description: 'Library management, cataloging, classification systems, digital library operations and information retrieval.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Librarian', 'Information Officer', 'Documentation Specialist', 'Archivist'],
    placementSupport: 'Schools, colleges and government library placements.',
    iconName: 'database',
  },
  {
    id: 'mlib',
    name: 'M.Lib - Master of Library Science',
    category: 'Library Science',
    subCategories: ['Postgraduate (PG)'],
    level: 'PG',
    duration: '1 Year',
    eligibility: 'B.Lib or equivalent',
    mode: 'Regular',
    badge: 'PG Program',
    description: 'Advanced library science with digital library systems, research database management and library administration.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['Senior Librarian', 'Library Administrator', 'Knowledge Manager', 'Digital Archivist'],
    placementSupport: 'University and government library placements.',
    iconName: 'database',
  },
  {
    id: 'dip-lib',
    name: 'Diploma in Library Science',
    category: 'Library Science',
    subCategories: ['Diploma Courses'],
    level: 'Diploma',
    duration: '6 Months',
    eligibility: '10+2 or equivalent',
    mode: 'Regular',
    badge: 'Diploma',
    description: 'Short-term diploma in library cataloging, book classification, library maintenance and basic documentation.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['Library Assistant', 'Book Keeper', 'Documentation Helper', 'School Librarian'],
    placementSupport: 'School and local government library placements.',
    iconName: 'database',
  },

  // ==================== ITI TRADES ====================
  {
    id: 'iti-elec',
    name: 'Electrician (ITI Trade)',
    category: 'ITI Trades',
    subCategories: ['Apprenticeship Programs', 'Government Approved Courses'],
    level: 'ITI',
    duration: '2 Years',
    eligibility: '10th Passed from any recognized board',
    mode: 'Regular',
    badge: 'NCVT Approved',
    description: 'DGT-approved practical trade covering domestic wiring, motor winding, generators, electrical panels and solar installations.',
    fees: 'Contact Admissions Desk',
    seats: 40,
    careerOpportunities: ['Licensed Contractor', 'Railway Technician', 'Grid Supervisor', 'Maintenance Operator'],
    placementSupport: 'NAPS apprenticeship support. Placed at Mahadiscom and railways.',
    iconName: 'bolt',
  },
  {
    id: 'iti-fitter',
    name: 'Fitter (ITI Trade)',
    category: 'ITI Trades',
    subCategories: ['Apprenticeship Programs', 'Government Approved Courses'],
    level: 'ITI',
    duration: '2 Years',
    eligibility: '10th Passed from any recognized board',
    mode: 'Regular',
    badge: 'Most Popular',
    description: 'Structural fitting, machinery piping, steel sheet fabrication, welding joints and component assembly workshop training.',
    fees: 'Contact Admissions Desk',
    seats: 40,
    careerOpportunities: ['Industrial Fitter', 'Assembly Technician', 'Maintenance Helper', 'Apprentice Fitter'],
    placementSupport: 'NAPS apprenticeship placement in manufacturing and auto plants.',
    iconName: 'wrench',
  },
  {
    id: 'iti-welder',
    name: 'Welder (ITI Trade)',
    category: 'ITI Trades',
    subCategories: ['Apprenticeship Programs', 'Government Approved Courses'],
    level: 'ITI',
    duration: '1 Year',
    eligibility: '8th / 10th Passed',
    mode: 'Regular',
    badge: 'Job Oriented',
    description: 'Gas welding, SMAW, TIG & MIG welding, plasma cutting and structural metal fabrication practical certification.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Structural Welder', 'Pipe Welder', 'Fabricator', 'Welding Inspector'],
    placementSupport: 'Direct linkages with heavy engineering workshops and automotive chassis makers.',
    iconName: 'flame',
  },
  {
    id: 'iti-copa',
    name: 'COPA (ITI Trade)',
    category: 'ITI Trades',
    subCategories: ['Government Approved Courses', 'Computer & IT'],
    level: 'ITI',
    duration: '1 Year',
    eligibility: '10th Passed',
    mode: 'Regular',
    badge: 'NCVT Approved',
    description: 'DGT-approved IT vocational trade covering office software, hardware troubleshooting, internet and database management.',
    fees: 'Contact Admissions Desk',
    seats: 40,
    careerOpportunities: ['Data Operator', 'Helpdesk Associate', 'Office Assistant', 'Computer Lab Operator'],
    placementSupport: 'Skill India certified job linkages with offices and institutions.',
    iconName: 'computer',
  },
  {
    id: 'iti-turner',
    name: 'Turner (ITI Trade)',
    category: 'ITI Trades',
    subCategories: ['Apprenticeship Programs', 'Government Approved Courses'],
    level: 'ITI',
    duration: '2 Years',
    eligibility: '10th Passed',
    mode: 'Regular',
    badge: 'Industry Ready',
    description: 'Precision lathe training: turning, taper turning, boring, thread cutting, screw configuration and milling adjustments.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['Lathe Turner', 'Toolroom Technician', 'Machinery Fitter', 'CNC Operator Trainee'],
    placementSupport: 'NAPS placements in precision manufacturing and metal workshops.',
    iconName: 'wrench',
  },
  {
    id: 'iti-machinist',
    name: 'Machinist (ITI Trade)',
    category: 'ITI Trades',
    subCategories: ['Apprenticeship Programs', 'Government Approved Courses'],
    level: 'ITI',
    duration: '2 Years',
    eligibility: '10th Passed',
    mode: 'Regular',
    badge: 'High Placement',
    description: 'Metal cutting and shaping with milling machines, shaping tools, surface grinders, slotting equipment and drill operations.',
    fees: 'Contact Admissions Desk',
    seats: 20,
    careerOpportunities: ['Milling Machine Operator', 'Precision Machinist', 'Tool Maker', 'Setter Technician'],
    placementSupport: 'Apprenticeship at heavy tooling plants and automotive vendors.',
    iconName: 'gear',
  },
  {
    id: 'iti-wireman',
    name: 'Wireman (ITI Trade)',
    category: 'ITI Trades',
    subCategories: ['Apprenticeship Programs', 'Government Approved Courses'],
    level: 'ITI',
    duration: '2 Years',
    eligibility: '8th / 10th Passed',
    mode: 'Regular',
    badge: 'Government Approved',
    description: 'Commercial and residential wiring layouts, distribution wiring, overhead line configurations and electrical installations.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Lineman Apprentice', 'Substation Helper', 'Domestic Wireman', 'Electrical Maintenance Helper'],
    placementSupport: 'Electrical infrastructure contractors and solar installers.',
    iconName: 'bolt',
  },
  {
    id: 'iti-diesel',
    name: 'Diesel Mechanic (ITI Trade)',
    category: 'ITI Trades',
    subCategories: ['Apprenticeship Programs', 'Government Approved Courses'],
    level: 'ITI',
    duration: '1 Year',
    eligibility: '10th Passed',
    mode: 'Regular',
    badge: 'Job Oriented',
    description: 'Diesel engine diagnostics, cooling and fuel injection systems, heavy machinery servicing and engine testing procedures.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Engine Service Technician', 'Fleet Mechanic', 'Locomotive Engine Apprentice', 'Auto Plant Operator'],
    placementSupport: 'Commercial garages and tractor plant apprenticeships.',
    iconName: 'gear',
  },
  {
    id: 'iti-rac',
    name: 'RAC Technician (ITI Trade)',
    category: 'ITI Trades',
    subCategories: ['Apprenticeship Programs', 'Government Approved Courses'],
    level: 'ITI',
    duration: '2 Years',
    eligibility: '10th Passed',
    mode: 'Regular',
    badge: 'Trending',
    description: 'Refrigerant gases, compressors, wiring, central ducting systems, compressor troubleshooting and refrigeration diagnostics.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['HVAC Technician', 'AC Repair Specialist', 'Cold Storage Specialist', 'Chiller Operator'],
    placementSupport: 'AC service networks and hotel maintenance departments.',
    iconName: 'sparkles',
  },
  {
    id: 'iti-elec-mech',
    name: 'Electronics Mechanic (ITI Trade)',
    category: 'ITI Trades',
    subCategories: ['Government Approved Courses'],
    level: 'ITI',
    duration: '2 Years',
    eligibility: '10th Passed with Science & Math',
    mode: 'Regular',
    badge: 'Industry Ready',
    description: 'Soldering, PCB designing, microcontrollers, digital circuit diagnostics and smart electronics assembly.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Electronics Technician', 'PCB Quality Controller', 'Smart Device Tester', 'Solar Inverter Assembler'],
    placementSupport: 'Consumer electronics manufacturers and solar vendors.',
    iconName: 'cpu',
  },
  {
    id: 'iti-plumber',
    name: 'Plumber (ITI Trade)',
    category: 'ITI Trades',
    subCategories: ['Government Approved Courses'],
    level: 'ITI',
    duration: '1 Year',
    eligibility: '8th / 10th Passed',
    mode: 'Regular',
    badge: 'Skill India',
    description: 'Piping joints, drainage systems, water motor configuration, leak diagnosis and bathroom fixture assembly.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['Maintenance Plumber', 'Pipefitting Installer', 'Sanitary Contractor', 'Project Helper'],
    placementSupport: 'Skill India portal direct job linkages.',
    iconName: 'wrench',
  },

  // ==================== SKILL DEVELOPMENT ====================
  {
    id: 'skill-cnc',
    name: 'CNC Operator Certification',
    category: 'Skill Development',
    subCategories: ['Apprenticeship Programs', 'Government Approved Courses'],
    level: 'Skill',
    duration: '6 Months',
    eligibility: '10th Passed or Fail',
    mode: 'Regular',
    badge: 'Skill India',
    description: 'Practical CNC mill settings, lathe configurations, blueprint readings, quality audits and shop safety procedures.',
    fees: 'Contact Admissions Desk',
    seats: 30,
    careerOpportunities: ['CNC Machinist', 'Toolroom Assistant', 'Component Inspector'],
    placementSupport: 'Direct linkages with automotive component manufacturers.',
    iconName: 'gear',
  },
  {
    id: 'skill-retail',
    name: 'Retail Management (Skill India)',
    category: 'Skill Development',
    subCategories: ['Government Approved Courses'],
    level: 'Skill',
    duration: '3 Months',
    eligibility: '10th / 12th Passed',
    mode: 'Hybrid',
    badge: 'Skill India',
    description: 'NSDC-aligned retail operations, store management, customer service, merchandising and POS system training.',
    fees: 'Contact Admissions Desk',
    seats: 40,
    careerOpportunities: ['Store Executive', 'Sales Associate', 'Cashier', 'Merchandiser'],
    placementSupport: 'Organized retail chains and franchise stores.',
    iconName: 'briefcase',
  },
  {
    id: 'skill-rural',
    name: 'Rural Development Program',
    category: 'Skill Development',
    subCategories: ['Government Approved Courses'],
    level: 'Skill',
    duration: '6 Months',
    eligibility: '10th Passed',
    mode: 'Regular',
    badge: 'Government Approved',
    description: 'Skill development for rural youth covering sustainable farming, local enterprise, basic IT literacy and financial inclusion.',
    fees: 'Contact Admissions Desk',
    seats: 40,
    careerOpportunities: ['Village Entrepreneur', 'Farmer Leader', 'Rural IT Worker', 'Self-Help Group Leader'],
    placementSupport: 'Government rural development program linkages.',
    iconName: 'network',
  },
  {
    id: 'skill-nsdc',
    name: 'NSDC Certificate Programs',
    category: 'Skill Development',
    subCategories: ['Government Approved Courses'],
    level: 'Certificate',
    duration: '3-6 Months',
    eligibility: '8th Passed',
    mode: 'Regular',
    badge: 'NSDC Approved',
    description: 'Short NSDC-certified vocational programs in multiple trades including hospitality, IT, retail and construction.',
    fees: 'Contact Admissions Desk',
    seats: 50,
    careerOpportunities: ['Trade Helper', 'Entry-Level Technician', 'Service Executive', 'Skilled Worker'],
    placementSupport: 'NSDC job portal linkages and placement fairs.',
    iconName: 'sparkles',
  },

  // ==================== APPRENTICESHIP PROGRAMS ====================
  {
    id: 'app-elec',
    name: 'Electrician Apprenticeship (NAPS)',
    category: 'Apprenticeship Programs',
    subCategories: ['ITI Trades', 'Government Approved Courses'],
    level: 'Apprenticeship',
    duration: '1-2 Years',
    eligibility: '10th Passed or ITI Electrician',
    mode: 'Regular',
    badge: 'NAPS Placed',
    description: 'Learn electrical circuits, panels and wire configurations on factory shop floors. Earn monthly NAPS stipends while training.',
    fees: 'Stipend Provided to Trainees',
    seats: 40,
    careerOpportunities: ['Licensed Contractor', 'Railway Technician', 'Grid Supervisor', 'Maintenance Operator'],
    placementSupport: 'Apprentice placements at industrial units and power utilities.',
    iconName: 'bolt',
  },
  {
    id: 'app-fitter',
    name: 'Fitter Apprenticeship (NAPS)',
    category: 'Apprenticeship Programs',
    subCategories: ['ITI Trades', 'Government Approved Courses'],
    level: 'Apprenticeship',
    duration: '1-2 Years',
    eligibility: '10th Passed or ITI Fitter',
    mode: 'Regular',
    badge: 'NAPS Placed',
    description: 'Engineering fitter training centered on heavy assembly lines. Earn monthly stipends under National Apprenticeship guidelines.',
    fees: 'Stipend Provided to Trainees',
    seats: 40,
    careerOpportunities: ['Industrial Fitter', 'Assembly Technician', 'Maintenance Helper', 'Apprentice Fitter'],
    placementSupport: 'Apprentice placements at automotive factories and heavy plants.',
    iconName: 'wrench',
  },
  {
    id: 'app-nsdc',
    name: 'NSDC Industry Training',
    category: 'Apprenticeship Programs',
    subCategories: ['Skill Development', 'Government Approved Courses'],
    level: 'Apprenticeship',
    duration: '6-12 Months',
    eligibility: '10th Passed or Skill Certificate',
    mode: 'Regular',
    badge: 'NSDC Approved',
    description: 'Industry-based training under NSDC guidelines across sectors including manufacturing, IT and services. Earn while you learn.',
    fees: 'Stipend Provided',
    seats: 50,
    careerOpportunities: ['Trade Apprentice', 'Industry Trainee', 'Sector Specialist', 'Technical Helper'],
    placementSupport: 'NSDC industry partner placement network.',
    iconName: 'network',
  },

  // ==================== GOVERNMENT APPROVED COURSES ====================
  {
    id: 'gov-skill-india',
    name: 'Skill India Programs',
    category: 'Government Approved Courses',
    subCategories: ['Skill Development'],
    level: 'Skill',
    duration: '3-12 Months',
    eligibility: '8th Passed onwards',
    mode: 'Regular',
    badge: 'Skill India',
    description: 'Government-certified Skill India courses aligned with National Skills Qualification Framework (NSQF) across multiple sectors.',
    fees: 'Contact Admissions Desk',
    seats: 60,
    careerOpportunities: ['Skilled Worker', 'Trade Specialist', 'Service Executive', 'Certified Technician'],
    placementSupport: 'National Skill Development Corporation job placement network.',
    iconName: 'sparkles',
  },
];
