export interface Course {
  id: string;
  name: string;
  category: string; // Primary sidebar category
  subCategories?: string[]; // Array of other categories it belongs to
  duration: string;
  eligibility: string;
  mode: 'Regular' | 'Online' | 'Hybrid';
  badge?: string; // e.g. "Most Popular", "New", "Placement Highlight", etc.
  description: string;
  fees: string; // Placeholder or fee range
  seats: number;
  careerOpportunities: string[];
  placementSupport: string;
  iconName: 'computer' | 'gear' | 'wrench' | 'briefcase' | 'database' | 'cpu' | 'building' | 'chart' | 'network' | 'bolt' | 'flame' | 'sparkles';
}

export const courseCategories = [
  "Engineering",
  "ITI Trades",
  "Polytechnic",
  "Diploma Engineering",
  "MBA",
  "Skill Development",
  "Apprenticeship",
  "Certificate Courses"
];

export const courseList: Course[] = [
  // ================= ENGINEERING COURSES =================
  {
    id: "eng-cse",
    name: "Computer Science Engineering",
    category: "Engineering",
    subCategories: ["Placement Programs"],
    duration: "4 Years",
    eligibility: "10+2 PCM with 50% marks",
    mode: "Regular",
    badge: "Most Popular",
    description: "In-depth study of computer science fundamentals, including software engineering, data structures, algorithms, databases, and advanced web development technologies.",
    fees: "Contact Admissions Desk",
    seats: 120,
    careerOpportunities: ["Software Developer", "Full Stack Engineer", "System Architect", "Database Administrator"],
    placementSupport: "Dedicated technical placement cell with direct corporate tie-ups.",
    iconName: "computer"
  },
  {
    id: "eng-ai-ds",
    name: "AI & Data Science",
    category: "Engineering",
    subCategories: ["Placement Programs"],
    duration: "4 Years",
    eligibility: "10+2 PCM with 50% marks",
    mode: "Regular",
    badge: "Trending",
    description: "Modern curriculum covering machine learning, data engineering, statistical modeling, neural networks, computer vision, and cognitive computing systems.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["AI Engineer", "Data Scientist", "Machine Learning Analyst", "Business Intelligence Dev"],
    placementSupport: "Specialized analytics placement support with tech companies.",
    iconName: "cpu"
  },
  {
    id: "eng-mech",
    name: "Mechanical Engineering",
    category: "Engineering",
    duration: "4 Years",
    eligibility: "10+2 PCM with 50% marks",
    mode: "Regular",
    badge: "Industry Ready",
    description: "Covers thermodynamics, fluid dynamics, manufacturing processes, CNC operations, robotics, machine design, and automotive technologies.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Design Engineer", "Plant Head", "Automotive Specialist", "Quality Control Lead"],
    placementSupport: "Direct industrial apprentice linkages with top auto & core industries.",
    iconName: "gear"
  },
  {
    id: "eng-civil",
    name: "Civil Engineering",
    category: "Engineering",
    duration: "4 Years",
    eligibility: "10+2 PCM with 50% marks",
    mode: "Regular",
    badge: "Top Choice",
    description: "Focuses on structural engineering, geotechnics, environmental engineering, concrete technology, structural designs, and modern survey techniques.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Site Engineer", "Structural Designer", "Project Estimator", "Urban Planner"],
    placementSupport: "Guidance for state and central government infrastructure contracts and corporate hiring.",
    iconName: "building"
  },
  {
    id: "eng-elec",
    name: "Electrical Engineering",
    category: "Engineering",
    duration: "4 Years",
    eligibility: "10+2 PCM with 50% marks",
    mode: "Regular",
    badge: "Job Oriented",
    description: "Deals with electrical power systems, power generation & transmission grids, electrical machines, control circuits, and renewable energy grids.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Power Grid Inspector", "Substation Engineer", "Electrical Design Analyst", "Maintenance Specialist"],
    placementSupport: "Assistance in state power utilities, railways, and private energy corporations.",
    iconName: "bolt"
  },
  {
    id: "eng-extc",
    name: "Electronics & Telecommunication",
    category: "Engineering",
    duration: "4 Years",
    eligibility: "10+2 PCM with 50% marks",
    mode: "Regular",
    badge: "Top Choice",
    description: "Focus on telecom networks, embedded systems, microcontrollers, VLSI designs, signal processing, and high-frequency communication pathways.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Telecom Network Engineer", "Embedded Systems Dev", "RF Analyst", "Electronics Designer"],
    placementSupport: "Placements with major telecommunication operators and semiconductor hardware firms.",
    iconName: "network"
  },
  {
    id: "eng-it",
    name: "Information Technology",
    category: "Engineering",
    subCategories: ["Placement Programs"],
    duration: "4 Years",
    eligibility: "10+2 PCM with 50% marks",
    mode: "Regular",
    badge: "High Placement",
    description: "Concentrates on cloud computing, cybersecurity, database administration, business networking, system admin, and digital transformation technologies.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Cloud Engineer", "Network Administrator", "Cybersecurity Analyst", "IT Project Manager"],
    placementSupport: "Corporate alignment with IT services companies and tech centers.",
    iconName: "database"
  },

  // ================= ITI TRADES =================
  {
    id: "iti-elec",
    name: "Diploma in Electrician",
    category: "ITI Trades",
    subCategories: ["Apprenticeship", "Placement Programs"],
    duration: "2 Years",
    eligibility: "10th Passed from any recognized board",
    mode: "Regular",
    badge: "Skill India",
    description: "Official DGT-approved practical trade course focusing on domestic wiring, motor winding, industrial generators, electrical panels, and solar installations.",
    fees: "Contact Admissions Desk",
    seats: 40,
    careerOpportunities: ["Licensed Contractor", "Railway Technician", "Grid Supervisor Helper", "Maintenance Operator"],
    placementSupport: "NAPS apprenticeship support with monthly stipend. Placed directly at Mahadiscom and railways.",
    iconName: "bolt"
  },
  {
    id: "iti-fitter",
    name: "Diploma in Fitter",
    category: "ITI Trades",
    subCategories: ["Apprenticeship", "Placement Programs"],
    duration: "2 Years",
    eligibility: "10th Passed from any recognized board",
    mode: "Regular",
    badge: "Most Popular",
    description: "Hands-on engineering workshop training covering structural fitting, machinery piping, steel sheet fabrication, welding joints, and component assembly.",
    fees: "Contact Admissions Desk",
    seats: 40,
    careerOpportunities: ["Industrial Fitter", "Assembly Technician", "Maintenance Helper", "Apprentice Fitter"],
    placementSupport: "NAPS apprenticeship placement in manufacturing and auto assembly plants.",
    iconName: "wrench"
  },
  {
    id: "iti-welder",
    name: "Diploma in Welder",
    category: "ITI Trades",
    subCategories: ["Apprenticeship", "Certificate Courses"],
    duration: "1 Year",
    eligibility: "8th / 10th Passed",
    mode: "Regular",
    badge: "Job Oriented",
    description: "Practical certification in Gas Welding, Shielded Metal Arc Welding (SMAW), TIG & MIG welding processes, plasma cutting, and structural metal fabrication.",
    fees: "Contact Admissions Desk",
    seats: 30,
    careerOpportunities: ["Structural Welder", "Pipe Welder", "Fabricator Assistant", "Quality Welder Inspector"],
    placementSupport: "Direct linkages with heavy engineering workshops and automotive chassis makers.",
    iconName: "flame"
  },
  {
    id: "iti-copa",
    name: "Diploma in COPA",
    category: "ITI Trades",
    subCategories: ["Certificate Courses"],
    duration: "1 Year",
    eligibility: "10th Passed",
    mode: "Regular",
    badge: "Top Choice",
    description: "DGT-approved vocational IT program covering office software packages, hardware troubleshooting, internet utilities, and database management query structures.",
    fees: "Contact Admissions Desk",
    seats: 40,
    careerOpportunities: ["Data Operator", "Helpdesk Associate", "Office Assistant", "Computer Lab Operator"],
    placementSupport: "Skill India certified job linkages with private offices and educational institutions.",
    iconName: "computer"
  },
  {
    id: "iti-turner",
    name: "Diploma in Turner",
    category: "ITI Trades",
    subCategories: ["Apprenticeship"],
    duration: "2 Years",
    eligibility: "10th Passed",
    mode: "Regular",
    badge: "Industry Ready",
    description: "Specialized precision lathe training: turning, taper turning, boring, thread-cutting, screw configuration, and milling adjustments.",
    fees: "Contact Admissions Desk",
    seats: 20,
    careerOpportunities: ["Lathe Turner", "Toolroom Technician", "Machinery Fitter", "CNC Trainee Operator"],
    placementSupport: "NAPS placements in precision manufacturing plants and metal workshops.",
    iconName: "wrench"
  },
  {
    id: "iti-machinist",
    name: "Diploma in Machinist",
    category: "ITI Trades",
    subCategories: ["Apprenticeship"],
    duration: "2 Years",
    eligibility: "10th Passed",
    mode: "Regular",
    badge: "High Placement",
    description: "Advanced metal cutting and shaping using milling machines, shaping tools, surface grinders, slotting equipment, and drill operations.",
    fees: "Contact Admissions Desk",
    seats: 20,
    careerOpportunities: ["Milling Machine Operator", "Precision Machinist", "Tool Maker Apprentice", "Setter Technician"],
    placementSupport: "Apprenticeship placement at heavy tooling plants and automotive vendors.",
    iconName: "gear"
  },
  {
    id: "iti-wireman",
    name: "Diploma in Wireman",
    category: "ITI Trades",
    subCategories: ["Apprenticeship"],
    duration: "2 Years",
    eligibility: "8th / 10th Passed",
    mode: "Regular",
    badge: "Government Approved",
    description: "Comprehensive training in commercial and residential layouts, distribution wiring, overhead line configurations, and electrical installations.",
    fees: "Contact Admissions Desk",
    seats: 30,
    careerOpportunities: ["Lineman Apprentice", "Substation Helper", "Domestic Wireman", "Electrical Maintenance Helper"],
    placementSupport: "Placement linkages with electrical infrastructure contractors and solar installers.",
    iconName: "bolt"
  },
  {
    id: "iti-diesel",
    name: "Diploma in Diesel Mechanic",
    category: "ITI Trades",
    subCategories: ["Apprenticeship"],
    duration: "1 Year",
    eligibility: "10th Passed",
    mode: "Regular",
    badge: "New",
    description: "Covers diesel engine diagnostics, cooling and fuel injection systems, heavy machinery servicing, engine tuning, and vehicle testing procedures.",
    fees: "Contact Admissions Desk",
    seats: 30,
    careerOpportunities: ["Engine Service Technician", "Fleet Mechanic Helper", "Locomotive Engine Apprentice", "Auto Plant Operator"],
    placementSupport: "Corporate apprenticeship opportunities at commercial garages and tractor plants.",
    iconName: "gear"
  },
  {
    id: "iti-rac",
    name: "Diploma in RAC Technician",
    category: "ITI Trades",
    subCategories: ["Apprenticeship"],
    duration: "2 Years",
    eligibility: "10th Passed",
    mode: "Regular",
    badge: "Trending",
    description: "Instruction in refrigerant gases, compressors, wiring, central ducting systems, compressor troubleshooting, and refrigeration cycle diagnostics.",
    fees: "Contact Admissions Desk",
    seats: 30,
    careerOpportunities: ["HVAC Technician", "AC Repair Specialist", "Cold Storage Maintenance Specialist", "Chiller Operator"],
    placementSupport: "Placement with air conditioning service networks and hotel maintenance departments.",
    iconName: "sparkles"
  },
  {
    id: "iti-elec-mech",
    name: "Diploma in Electronics Mechanic",
    category: "ITI Trades",
    duration: "2 Years",
    eligibility: "10th Passed with Science & Math",
    mode: "Regular",
    badge: "Industry Ready",
    description: "Detailed training on soldering techniques, PCB designing, microcontrollers, digital circuit diagnostics, and smart electronics assembly.",
    fees: "Contact Admissions Desk",
    seats: 30,
    careerOpportunities: ["Electronics Repair Technician", "PCB Quality Controller", "Smart Device Tester", "Solar Inverter Assembly Helper"],
    placementSupport: "Direct linkages with consumer electronics manufacturers and solar vendors.",
    iconName: "cpu"
  },
  {
    id: "iti-surveyor",
    name: "Diploma in Surveyor",
    category: "ITI Trades",
    duration: "2 Years",
    eligibility: "10th Passed",
    mode: "Regular",
    badge: "Job Oriented",
    description: "Learn chain surveying, plane tables, auto-levels, total station GPS mapping coordinates, contour lines, and topography documentation.",
    fees: "Contact Admissions Desk",
    seats: 20,
    careerOpportunities: ["Land Surveyor Assistant", "Road Construction Estimator", "Mine Topography Assistant", "CAD Draftsman"],
    placementSupport: "Placements with civil construction firms and infrastructure agencies.",
    iconName: "building"
  },
  {
    id: "iti-plumber",
    name: "Diploma in Plumber",
    category: "ITI Trades",
    duration: "1 Year",
    eligibility: "8th / 10th Passed",
    mode: "Regular",
    badge: "Skill India",
    description: "Practical instruction in piping joints, drainage systems, water motor configurations, leak diagnosis, and bathroom fixture assembly.",
    fees: "Contact Admissions Desk",
    seats: 30,
    careerOpportunities: ["Maintenance Plumber", "Pipefitting Installer", "Sanitary Contractor", "Project Helper"],
    placementSupport: "Skill India portal direct job linkages and residential maintenance cells.",
    iconName: "wrench"
  },

  // ================= MBA SPECIALIZATIONS =================
  {
    id: "mba-mkt",
    name: "MBA Marketing",
    category: "MBA",
    subCategories: ["Placement Programs"],
    duration: "2 Years",
    eligibility: "Graduate in any stream",
    mode: "Hybrid",
    badge: "Most Popular",
    description: "Advanced management training focusing on consumer analytics, branding, advertising, digital growth strategies, and strategic sales management.",
    fees: "Contact Admissions Desk",
    seats: 30,
    careerOpportunities: ["Marketing Director", "Brand Manager", "Sales strategist", "Market Analyst"],
    placementSupport: "Corporate placements with top FMCG, retail, and digital marketing agencies.",
    iconName: "chart"
  },
  {
    id: "mba-fin",
    name: "MBA Finance",
    category: "MBA",
    subCategories: ["Placement Programs"],
    duration: "2 Years",
    eligibility: "Graduate in any stream",
    mode: "Hybrid",
    badge: "Top Choice",
    description: "In-depth training on corporate finance structure, investment portfolios, wealth management, risk models, and quantitative financial structures.",
    fees: "Contact Admissions Desk",
    seats: 30,
    careerOpportunities: ["Financial Controller", "Investment Banking Analyst", "Portfolio Manager", "Credit Risk Officer"],
    placementSupport: "Tie-ups with private banks, fintech startups, and audit consultants.",
    iconName: "briefcase"
  },
  {
    id: "mba-hr",
    name: "MBA Human Resource",
    category: "MBA",
    duration: "2 Years",
    eligibility: "Graduate in any stream",
    mode: "Hybrid",
    badge: "Job Oriented",
    description: "Covers employee relations, conflict management, organization design, talent acquisitions, reward models, and labor compliance guidelines.",
    fees: "Contact Admissions Desk",
    seats: 20,
    careerOpportunities: ["HR Manager", "Talent Acquisition Head", "Corporate Trainer", "HR Operations Lead"],
    placementSupport: "Dedicated HR placement channels with service and tech firms.",
    iconName: "network"
  },
  {
    id: "mba-ops",
    name: "MBA Operations",
    category: "MBA",
    duration: "2 Years",
    eligibility: "Graduate in any stream",
    mode: "Hybrid",
    badge: "Industry Ready",
    description: "Optimize operations processes, warehousing protocols, quality methodologies (Six Sigma), procurement logic, and project management standards.",
    fees: "Contact Admissions Desk",
    seats: 20,
    careerOpportunities: ["Operations Analyst", "Warehouse Manager", "Quality Head", "Supply Chain Analyst"],
    placementSupport: "Direct placements at leading automotive, manufacturing, and logistic firms.",
    iconName: "gear"
  },
  {
    id: "mba-analytics",
    name: "MBA Business Analytics",
    category: "MBA",
    subCategories: ["Placement Programs"],
    duration: "2 Years",
    eligibility: "Graduate in any stream",
    mode: "Hybrid",
    badge: "Trending",
    description: "Modern curriculum blending data management with business strategy. Learn predictive systems, dashboarding tools, and statistics-backed decision models.",
    fees: "Contact Admissions Desk",
    seats: 10,
    careerOpportunities: ["Business Analyst", "Data Strategy Consultant", "Data Visualization Expert", "Analytics Lead"],
    placementSupport: "Placements with consulting firms and tech services organizations.",
    iconName: "chart"
  },
  {
    id: "mba-dig-mkt",
    name: "MBA Digital Marketing",
    category: "MBA",
    duration: "2 Years",
    eligibility: "Graduate in any stream",
    mode: "Online",
    badge: "New",
    description: "Focuses on Search Engine Optimization (SEO), Paid Ads (SEM), social media operations, content strategies, email analytics, and brand building.",
    fees: "Contact Admissions Desk",
    seats: 20,
    careerOpportunities: ["Growth Marketer", "SEO Director", "Digital Campaigns Lead", "Content strategist"],
    placementSupport: "Collaborations with agency partners and product corporations.",
    iconName: "computer"
  },
  {
    id: "mba-ib",
    name: "MBA International Business",
    category: "MBA",
    duration: "2 Years",
    eligibility: "Graduate in any stream",
    mode: "Hybrid",
    badge: "Government Approved",
    description: "Understand cross-border trade guidelines, international trade finance, global compliance networks, and multinational corporate logistics.",
    fees: "Contact Admissions Desk",
    seats: 10,
    careerOpportunities: ["Global Logistics Manager", "International Trade Specialist", "Cross-Border strategist", "Export-Import Head"],
    placementSupport: "Trade corporations and global freight organizations.",
    iconName: "network"
  },
  {
    id: "mba-scm",
    name: "MBA Supply Chain",
    category: "MBA",
    duration: "2 Years",
    eligibility: "Graduate in any stream",
    mode: "Hybrid",
    badge: "Industry Ready",
    description: "Focus on freight operations, demand planning structures, raw materials procurement, container layouts, and vendor quality management.",
    fees: "Contact Admissions Desk",
    seats: 10,
    careerOpportunities: ["Supply Chain Coordinator", "Logistics Analyst", "Procurement strategist", "Inventory Controller"],
    placementSupport: "Direct placement with e-commerce firms, shipping operators, and retailers.",
    iconName: "briefcase"
  },
  {
    id: "mba-hospital",
    name: "MBA Hospital Management",
    category: "MBA",
    duration: "2 Years",
    eligibility: "Graduate in any stream",
    mode: "Hybrid",
    badge: "Top Choice",
    description: "Covers hospital layouts, clinical process audits, public health policies, medical insurance frameworks, and healthcare infrastructure management.",
    fees: "Contact Admissions Desk",
    seats: 10,
    careerOpportunities: ["Hospital Administrator", "Healthcare Facility Planner", "Clinical Audit Coordinator", "Medical Operations Head"],
    placementSupport: "Placements with hospital chains, healthcare trusts, and insurance providers.",
    iconName: "building"
  },
  {
    id: "mba-retail",
    name: "MBA Retail Management",
    category: "MBA",
    duration: "2 Years",
    eligibility: "Graduate in any stream",
    mode: "Hybrid",
    badge: "Skill India",
    description: "Advanced training in multi-channel retailing, franchise networks, retail audits, store customer engagement, and inventory layout design.",
    fees: "Contact Admissions Desk",
    seats: 10,
    careerOpportunities: ["Store Director", "Retail Operations Analyst", "Merchandising Coordinator", "Franchise Coordinator"],
    placementSupport: "Direct channels with organized retail groups and consumer brands.",
    iconName: "briefcase"
  },
  {
    id: "mba-ent",
    name: "MBA Entrepreneurship",
    category: "MBA",
    duration: "2 Years",
    eligibility: "Graduate in any stream",
    mode: "Hybrid",
    badge: "Trending",
    description: "New venture creation training: business blueprints, investor pitches, capital valuations, intellectual property, and team building.",
    fees: "Contact Admissions Desk",
    seats: 10,
    careerOpportunities: ["Startup Founder", "Venture Partner Analyst", "Incubator Specialist", "Innovation Director"],
    placementSupport: "Direct linkages with startup incubators, seed funds, and acceleration labs.",
    iconName: "sparkles"
  },
  {
    id: "mba-it-mgmt",
    name: "MBA IT Management",
    category: "MBA",
    duration: "2 Years",
    eligibility: "Graduate in any stream",
    mode: "Hybrid",
    badge: "Job Oriented",
    description: "Bridge between system management and business: tech resources allocation, software lifecycle management, security audits, and cloud strategies.",
    fees: "Contact Admissions Desk",
    seats: 10,
    careerOpportunities: ["IT Infrastructure Lead", "Chief Technology Officer Trainee", "Tech Project Analyst", "IT Vendor Manager"],
    placementSupport: "Collaborations with global consulting desks and systems integrators.",
    iconName: "cpu"
  },

  // ================= POLYTECHNIC =================
  {
    id: "poly-mech",
    name: "Mechanical Diploma",
    category: "Polytechnic",
    subCategories: ["Diploma Engineering"],
    duration: "3 Years",
    eligibility: "10th Passed with Science & Math",
    mode: "Regular",
    badge: "Industry Ready",
    description: "A compact engineering diploma focusing on metal cutting, blueprints, CNC settings, automotive systems, and structural mechanics lab operations.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Junior Design Engineer", "CNC Shop Floor Operator", "Auto Service Supervisor", "Maintenance Technician"],
    placementSupport: "Direct apprenticeships and placements with core industrial factories.",
    iconName: "gear"
  },
  {
    id: "poly-civil",
    name: "Civil Diploma",
    category: "Polytechnic",
    subCategories: ["Diploma Engineering"],
    duration: "3 Years",
    eligibility: "10th Passed with Science & Math",
    mode: "Regular",
    badge: "Government Approved",
    description: "Covers basic building drafting, soil testing procedures, concrete layouting, survey equipment operations, and project estimation.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Site Surveyor", "Assistant Site Engineer", "Draftsman Operator", "Civil Estimator Helper"],
    placementSupport: "Assistance in state contractor registrations and construction companies.",
    iconName: "building"
  },
  {
    id: "poly-comp",
    name: "Computer Diploma",
    category: "Polytechnic",
    subCategories: ["Diploma Engineering", "Placement Programs"],
    duration: "3 Years",
    eligibility: "10th Passed with Science & Math",
    mode: "Regular",
    badge: "Most Popular",
    description: "Fundamentals of coding, script troubleshooting, hardware installations, database connections, and web layouts construction.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Junior Web Developer", "IT Support Specialist", "Network Operations Associate", "Testing Assistant"],
    placementSupport: "Direct placements at IT services firms and system integrators.",
    iconName: "computer"
  },
  {
    id: "poly-elec",
    name: "Electrical Diploma",
    category: "Polytechnic",
    subCategories: ["Diploma Engineering"],
    duration: "3 Years",
    eligibility: "10th Passed with Science & Math",
    mode: "Regular",
    badge: "Job Oriented",
    description: "Detailed instruction in power networks, substation layouts, motor systems repair, domestic grid installations, and wiring blueprint reviews.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Electrical Substation Helper", "Maintenance Operator Assistant", "Solar Wiring Operator", "Power Inspector Trainee"],
    placementSupport: "Linkages with energy infrastructure contractors and state utilities.",
    iconName: "bolt"
  },
  {
    id: "poly-elec-comm",
    name: "Electronics Diploma",
    category: "Polytechnic",
    subCategories: ["Diploma Engineering"],
    duration: "3 Years",
    eligibility: "10th Passed with Science & Math",
    mode: "Regular",
    badge: "Top Choice",
    description: "Fundamentals of electronic devices, circuit layouts, PCB soldering, microcontrollers coding, and basic device repair.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Junior Hardware Tester", "PCB Layout Technician", "Device Repair specialist", "Electronics Assembly Coordinator"],
    placementSupport: "Placements with hardware parts makers and solar panels firms.",
    iconName: "cpu"
  },

  // ================= DIPLOMA ENGINEERING (aliases) =================
  {
    id: "dip-mech",
    name: "Mechanical Diploma",
    category: "Diploma Engineering",
    subCategories: ["Polytechnic"],
    duration: "3 Years",
    eligibility: "10th Passed with Science & Math",
    mode: "Regular",
    badge: "Industry Ready",
    description: "Compact study of mechanics, tool engineering, materials properties, thermodynamics, production design, and CNC operations.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Junior Design Engineer", "CNC Shop Floor Operator", "Auto Service Supervisor", "Maintenance Technician"],
    placementSupport: "Direct apprenticeships and placements with core industrial factories.",
    iconName: "gear"
  },
  {
    id: "dip-civil",
    name: "Civil Diploma",
    category: "Diploma Engineering",
    subCategories: ["Polytechnic"],
    duration: "3 Years",
    eligibility: "10th Passed with Science & Math",
    mode: "Regular",
    badge: "Government Approved",
    description: "Covers building layouts, leveling methods, materials specifications, concrete checks, and site safety management.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Site Surveyor", "Assistant Site Engineer", "Draftsman Operator", "Civil Estimator Helper"],
    placementSupport: "Assistance in state contractor registrations and construction companies.",
    iconName: "building"
  },
  {
    id: "dip-comp",
    name: "Computer Diploma",
    category: "Diploma Engineering",
    subCategories: ["Polytechnic", "Placement Programs"],
    duration: "3 Years",
    eligibility: "10th Passed with Science & Math",
    mode: "Regular",
    badge: "Most Popular",
    description: "Fundamentals of computer networks, assembly programming, data management, web layout designing, and systems security setups.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Junior Web Developer", "IT Support Specialist", "Network Operations Associate", "Testing Assistant"],
    placementSupport: "Direct placements at IT services firms and system integrators.",
    iconName: "computer"
  },
  {
    id: "dip-elec",
    name: "Electrical Diploma",
    category: "Diploma Engineering",
    subCategories: ["Polytechnic"],
    duration: "3 Years",
    eligibility: "10th Passed with Science & Math",
    mode: "Regular",
    badge: "Job Oriented",
    description: "Covers industrial control panels wiring, generators servicing, substation engineering, instrumentation loops, and renewable grids.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Electrical Substation Helper", "Maintenance Operator Assistant", "Solar Wiring Operator", "Power Inspector Trainee"],
    placementSupport: "Linkages with energy infrastructure contractors and state utilities.",
    iconName: "bolt"
  },
  {
    id: "dip-elec-comm",
    name: "Electronics Diploma",
    category: "Diploma Engineering",
    subCategories: ["Polytechnic"],
    duration: "3 Years",
    eligibility: "10th Passed with Science & Math",
    mode: "Regular",
    badge: "Top Choice",
    description: "Deals with PCB etching, semiconductor diagnostic instruments, basic microcontroller programming, and assembly checks.",
    fees: "Contact Admissions Desk",
    seats: 60,
    careerOpportunities: ["Junior Hardware Tester", "PCB Layout Technician", "Device Repair specialist", "Electronics Assembly Coordinator"],
    placementSupport: "Placements with hardware parts makers and solar panels firms.",
    iconName: "cpu"
  },

  // ================= SKILL DEVELOPMENT =================
  {
    id: "skill-cnc",
    name: "CNC Operator Certification",
    category: "Skill Development",
    subCategories: ["Apprenticeship", "Certificate Courses"],
    duration: "6 Months",
    eligibility: "10th Passed or Fail",
    mode: "Regular",
    badge: "Skill India",
    description: "Practical course covering CNC mill settings, lathe configurations, blueprint readings, quality audits, and shop safety procedures.",
    fees: "Contact Admissions Desk",
    seats: 30,
    careerOpportunities: ["CNC Machinist Operator", "Toolroom Assistant", "Component Inspector"],
    placementSupport: "Direct linkages with automotive components manufacturers in regional areas.",
    iconName: "gear"
  },
  {
    id: "skill-sales",
    name: "Sales & Marketing Certification",
    category: "Skill Development",
    subCategories: ["Certificate Courses"],
    duration: "6 Months",
    eligibility: "10th / 12th Passed",
    mode: "Hybrid",
    badge: "Job Oriented",
    description: "Practical sales pitch frameworks, store merchandising systems, retail operations, customer care logic, and presentation guidelines.",
    fees: "Contact Admissions Desk",
    seats: 40,
    careerOpportunities: ["Sales Associate", "Customer Executive", "Billing Assistant"],
    placementSupport: "Job placements at local showrooms, organized retail stores, and service companies.",
    iconName: "briefcase"
  },

  // ================= APPRENTICESHIP =================
  {
    id: "app-elec",
    name: "Electrician (Apprenticeship)",
    category: "Apprenticeship",
    subCategories: ["ITI Trades", "Placement Programs"],
    duration: "2 Years",
    eligibility: "10th Passed from any recognized board",
    mode: "Regular",
    badge: "NAPS Placed",
    description: "Learn electrical circuits, panels repair, and wire configurations on factory shop-floors. Earn monthly NAPS stipends while training.",
    fees: "Stipend Provided to Trainees",
    seats: 40,
    careerOpportunities: ["Licensed Contractor", "Railway Technician", "Grid Supervisor Helper", "Maintenance Operator"],
    placementSupport: "Apprentice placements at industrial units and power utilities.",
    iconName: "bolt"
  },
  {
    id: "app-fitter",
    name: "Fitter (Apprenticeship)",
    category: "Apprenticeship",
    subCategories: ["ITI Trades", "Placement Programs"],
    duration: "2 Years",
    eligibility: "10th Passed from any recognized board",
    mode: "Regular",
    badge: "NAPS Placed",
    description: "Practical engineering fitter training centered on heavy assembly lines. Earn monthly stipends under National Apprenticeship guidelines.",
    fees: "Stipend Provided to Trainees",
    seats: 40,
    careerOpportunities: ["Industrial Fitter", "Assembly Technician", "Maintenance Helper", "Apprentice Fitter"],
    placementSupport: "Apprentice placements at automotive factories and heavy plants.",
    iconName: "wrench"
  },

  // ================= CERTIFICATE COURSES =================
  {
    id: "cert-copa",
    name: "COPA Certificate",
    category: "Certificate Courses",
    subCategories: ["ITI Trades", "Skill Development"],
    duration: "1 Year",
    eligibility: "10th Passed",
    mode: "Regular",
    badge: "Skill India",
    description: "Short vocational certificate for database queries, system administrative tools, office scripts, and spreadsheet processing.",
    fees: "Contact Admissions Desk",
    seats: 40,
    careerOpportunities: ["Computer Operator", "Data Entry Specialist", "Office Clerk"],
    placementSupport: "Job linkage portals and regional listings.",
    iconName: "computer"
  }
];
