module.exports = [
  { name: "Bachelor of Business Administrative (BBA)", category: "Management", duration: "3 Years", eligibility: "12th pass" },
  { name: "Master of Business Administration (MBA)", category: "Management", duration: "2 Years", eligibility: "Graduation in any Discipline" },
  { name: "Executive MBA", category: "Management", duration: "1 Year", eligibility: "Graduation in any Discipline" },
  { name: "Post Graduate Diploma in Business Management (PGDBM)", category: "Management", duration: "1 Year", eligibility: "Graduation in any Discipline" },
  { name: "Diploma in Computer Application (DCA)", category: "Computer & IT", duration: "1 Year", eligibility: "12th Pass" },
  { name: "Post Graduate Diploma in Computer Application (PGDCA)", category: "Computer & IT", duration: "1 Year", eligibility: "Graduation in Any Discipline" },
  { name: "Bachelor of Computer Application (BCA)", category: "Computer & IT", duration: "3 Year", eligibility: "12th Pass" },
  { name: "Master of Science in Information Technology (M.Sc.IT)", category: "Computer & IT", duration: "2 Year", eligibility: "Graduation In Any Discipline" },
  { name: "Master of Computer Application (MCA)", category: "Computer & IT", duration: "3 Year", eligibility: "Graduation In Any Discipline With 10+2 Math Sciences" },
  { name: "Bachelor of Science (B.Sc) (Math)", category: "Science", duration: "3 Years", eligibility: "12th in Math" },
  { name: "Bachelor of Science (B.Sc) (Biology)", category: "Science", duration: "3 Years", eligibility: "12th in Biology" },
  { name: "Master of Science (M.Sc) (Math)", category: "Science", duration: "2 Years", eligibility: "Graduation In B.Sc. (Math)" },
  { name: "Bachelor of Science (M.Sc) (Physics)", category: "Science", duration: "2 Years", eligibility: "Graduation in B.Sc. (Math)" },
  { name: "Bachelor of Science (M.Sc) (Chemistry)", category: "Science", duration: "2 Years", eligibility: "Graduation in B.Sc (Maths) B.Sc (Biology)" },
  { name: "Diploma in Mechanical Engg.", category: "Engineering", duration: "3 Years", eligibility: "10th Pass" },
  { name: "Diploma in Computer Engg.", category: "Engineering", duration: "3 Years", eligibility: "10th Pass" },
  { name: "Diploma in Electrical Engg.", category: "Engineering", duration: "3 Years", eligibility: "10th Pass" },
  { name: "Diploma in Electronics Engg.", category: "Engineering", duration: "3 Years", eligibility: "10th Pass" },
  { name: "Diploma in Civil Engg.", category: "Engineering", duration: "3 Years", eligibility: "10th Pass" },
  { name: "B.Tech. (all stream)", category: "Engineering", duration: "4 Years", eligibility: "10+2 Pass" },
  { name: "Bachelor of Commerce (B.Com)", category: "Commerce", duration: "3 Years", eligibility: "12th Pass From Science & Commerce" },
  { name: "Bachelor of Commerce (M.Com)", category: "Commerce", duration: "2 Years", eligibility: "Graduate in B.Com" },
  { name: "Bachelor of Arts (B.A.)", category: "Arts & Humanities", duration: "3 Years", eligibility: "12th Pass" },
  { name: "Master of Art (M.A)", category: "Arts & Humanities", duration: "2 Years", eligibility: "Graduation" },
  { name: "Master of Social Work (MSW)", category: "Arts & Humanities", duration: "2 Years", eligibility: "Graduation In Any Discipline" },
  { name: "B. Lib.", category: "Arts & Humanities", duration: "1 Year", eligibility: "Graduation" },
  { name: "M. Lib.", category: "Arts & Humanities", duration: "1 Year", eligibility: "B. Lib+ Graduation" },
  { name: "B.J.M.S.", category: "Arts & Humanities", duration: "1 Year", eligibility: "Graduation" },
  { name: "M.J.M.S.", category: "Arts & Humanities", duration: "1 Year", eligibility: "Graduation +BJMS" },
];
